# 定义 image
# image: node:10.15.0

# 定义 stages
stages:
  - install_build_deploy

# 设置缓存
# ps: 只有一个 job 就不用设置缓存了
# cache:
#   key: ${CI_COMMIT_REF_NAME}
#   paths:
#     - node_modules/
#     - md/

# before_script:
# ps: 提供一种思路
#   - PATH=/usr/local/node/bin:$PATH
#   - export PATH
#   - whoami
#   - pwd
#   - echo $PATH


# 定义 job
job_install_build_deploy:
  stage: install_build_deploy
  # when: manual
  only:
    - master
  script:
    # 打印一些相关信息
    - pwd
    - whoami
    # 安装依赖
    - echo "Starting job_install"
    - npm install
    # 打包构建
    - echo "Starting job_build"
    - npm run build
    # 部署
    - echo "Starting deploy"
    - sudo rm -rf /var/data/sword/md
    - sudo cp -r md /var/data/sword
