# 定义 image
image: node:10

# 定义 stages
stages:
  - install_build_deploy

# 设置缓存
# cache:
#   key: ${CI_COMMIT_REF_NAME}
#   paths:
#     - node_modules/
#     - md/

# before_script:
#   - PATH=/usr/local/node/bin:$PATH
#   - export PATH
#   - whoami
#   - pwd
#   - echo $PATH

before_script:
  - echo "Starting job_install"
  - ls -al
  - node -v
  - npm -v
  - npm install

# 定义 job
job_install_build_deploy:
  stage: install_build_deploy
  # when: manual
  script:
    - echo "Starting job_build"
    - npm run build
    - echo "Starting deploy"
    - rm -rf /var/data/sword/md
    - copy md/ /var/data/sword
